{359}{412}Avant de voir le spectacle | très inhabituel qui va suivre,
{412}{501}quelques explications | sont nécessaires...
{501}{573}AUSSI INCROYABLE | QUE CELA PUISSE PARAITRE...
{573}{644}Autrefois, tout ce qui | s'éloignait des normes
{644}{786}était vu comme un mauvais présage
{786}{858}ou comme l'incarnation du mal.
{858}{1002}Les dieux de la malchance | étaient toujours représentés
{1002}{1074}sous la forme de monstres.
{1074}{1143}Et l'on a attribué | bien des injustices
{1143}{1215}aux nombreux tyrans contrefaits, | déformés, d'Europe et d'Asie.
{1215}{1287}HISTOIRE, RELIGION, | FOLKLORE et LITTERATURE
{1287}{1359}regorgent de récits | de personnages difformes
{1359}{1431}qui ont changé | le cours de l'histoire.
{1431}{1500}GOLIATH, CALABAN | FRANKENSTEIN,
{1500}{1572}GLOUCESTER, TOM POUCE | et KAISER WILHELM,
{1572}{1644}pour ne citer qu'eux, | sont connus dans le monde entier.
{1644}{1716}La naissance d'un enfant anormal | était une honte
{1716}{1788}et ceux atteints de difformités | étaient abandonnés dans la nature
{1788}{1858}pour y mourir. | Si par chance l'un d'eux survivait,
{1858}{1930}on le considérait comme suspect.
{1930}{2001}Les gens le fuyaient | à cause de son infirmité
{2001}{2073}et toute famille concernée | se sentait honteuse
{2073}{2145}d'une telle malédiction.
{2145}{2215}Parfois, on amenait | un de ces malheureux au tribunal
{2215}{2287}pour se moquer de lui | au grand amusement de la noblesse.
{2287}{2359}D'autres devaient mendier | et voler pour survivre.
{2359}{2431}Le culte de la beauté est un | sentiment profondément enraciné
{2431}{2503}qui remonte au début | de la civilisation.
{2503}{2572}La répulsion que nous cause | la vue des anormaux, des mutilés,
{2572}{2644}résulte d'un conditionnement | hérité de nos ancêtres.
{2644}{2716}La plupart des monstres ont des | pensées et des émotions normales.
{2716}{2788}Leur sort est vraiment tragique.
{2788}{2860}Ils sont obligés | de mener une vie anormale.
{2860}{2929}Ils ont donc établi entre eux | un code de moralité
{2929}{3001}pour se protéger des critiques | des gens normaux.
{3001}{3073}Les règles sont suivies | strictement.
{3073}{3145}Ce qui blesse l'un | blesse tous les autres,
{3145}{3217}et ce qui réjouit l'un | réjouit tous les autres.
{3217}{3287}L'histoire qui va être racontée
{3287}{3359}est fondée sur les conséquences | de ce code dans leur vie.
{3359}{3430}Jamais plus une telle histoire | ne pourra être filmée,
{3430}{3500}puisque la science moderne | élimine rapidement
{3500}{3560}ces erreurs de la nature | de la planète.
{3560}{3596}Face à toutes les injustices | subies par ces gens
{3596}{3656}qui ne sont pas responsables | de leur sort,
{3656}{3716}c'est humblement | que nous présentons
{3716}{3769}l'histoire effroyable | des ANORMAUX
{3769}{3800}et des INDÉSIRABLES.
{3873}{4095}LA MONSTRUEUSE PARADE
{4230}{4270}Nous ne vous avons pas menti.
{4280}{4340}Nous vous avons annoncé des monstres.
{4350}{4410}Et vous avez eu des monstres !
{4430}{4500}Ils vous ont fait rire... | et trembler.
{4520}{4590}Pourtant si le hasard l'avait voulu -
{4620}{4660}...vous pourriez être l'un d'eux.
{4720}{4767}Ils n'ont pas | demandé à naître...
{4777}{4840}mais ils sont nés | et ils vivent.
{4870}{4930}Ils ont leur code... | leurs lois.
{4979}{5030}Offenser l'un d'eux -
{5035}{5080}...c'est les offenser tous.
{5190}{5270}A présent, si vous voulez bien | me suivre...
{5290}{5370}...vous allez voir la plus | extraordinaire -
{5380}{5475}...la plus monstrueuse | créature.
{5490}{5524}...de tous les temps.
{5650}{5710}- Amis -
{5730}{5814}Ce fut jadis une beauté.
{5850}{5890}Un prince de sang | royal -
{5892}{5958}... se suicida pour elle.
{5982}{6050}On l'appelait | "l'oiseau de paradis" !
{6300}{6410}Je n'ai jamais vu grande | femme plus belle.
{6415}{6440}Voyons Hans...
{6450}{6537}Tu vas me rendre jalouse !
{6545}{6600}Ne dis pas de sottises.
{6630}{6680}J'en ai vu de ces femmes -
{6682}{6736}...faire les yeux doux | à mon Hans.
{6760}{6807}Mais je ne suis pas jalouse.
{6838}{6874}Frieda ma chérie...
{6885}{6945}...je n'ai d'yeux | que pour une femme.
{6974}{7090}Celle que je vais épouser, toi.
{8395}{8438}Je vous fais rire ?
{8445}{8475}Mais non monsieur.
{8478}{8514}J'en suis heureux.
{8532}{8565}Pourquoi je rirais de vous ?
{8575}{8615}Les grands rient de moi...
{8625}{8735}Les petits n'éprouvent rien | selon eux.
{8930}{9030}Vous êtes si gentils.
{9230}{9270}Très joli...
{9725}{9765}Venez me voir un soir.
{9775}{9827}Nous prendrons l'apéritif.
{10199}{10295}J'ai pensé que j'imaginais | des choses.
{10355}{10424}Je n'en croyais pas mes yeux.
{10426}{10550}Ces créatures horribles, | rampant, gémissant...
{10552}{10606}Vous n'avez rien bu | hier soir.
{10606}{10660}Rien Monsieur. | Je vous l'assure.
{10847}{10940}Il devrait y avoir une loi | contre ces gens.
{10960}{11010}On devrait les enfermer.
{11020}{11090}S'ils sont encore ici, | chassez-les.
{11630}{11673}Allez vous-en tous.
{11824}{11890}C'est une propriété privée | ici.
{11920}{12014}Pardon Monsieur. | Je suis Mme Tatrallini.
{12035}{12099}Ces--enfants | viennent de mon cirque.
{12116}{12130}Des enfants.. !
{12175}{12230}Le cirque...Je comprends.
{12269}{12312}Quand l'occasion se présente -
{12325}{12388}...je les emmène au Soleil -
{12390}{12456}...pour qu'ils jouent | comme des--enfants.
{12490}{12560}Voyez-vous, | c'est ce qu'ils sont :
{12580}{12624}Des enfants.
{12705}{12726}Des enfants...
{12870}{12910}Toutes mes excuses Madame.
{12915}{12965}Restez autant | qu'il vous plaira.
{13245}{13270}Combien de fois | je vous ai dit -
{13290}{13331}...de ne pas avoir peur ?
{13390}{13477}Dieu veille sur | tous ses enfants.
{13744}{13774}Bonsoir Madame.
{13792}{13855}Il y a foule ce soir | Madame Tatrallini.
{13955}{14017}Elle va promener | ses monstres !
{14073}{14120}Une galerie | des horreurs ambulante !
{14158}{14205}Aussi hideux que | sur les affiches...
{14215}{14255}Mais en chair et en os.
{14264}{14309}Les plus beaux monstres | vivants !
{14320}{14406}Joséphine-Joseph, | mi-femme, mi-homme !
{14427}{14464}Un cigare Joseph ?
{14465}{14515}Ton rouge à lèvre Joséphine !
{14520}{14589}Enerve Joséphine, | et Joseph te mettra KO !
{14910}{14986}C'est p-p-pas vrai !
{14995}{15038}Pourquoi tu as fait ça ?
{15055}{15105}Tu c-c-comprends pas.
{15130}{15215}Une noble romaine qui | descend de taureau -
{15216}{15255}...en se grattant !
{15256}{15321}Les n-n-nobles | se grattent pas ?
{15350}{15380}Prends plutôt un bain !
{15381}{15450}C'est le taureau qui | a besoin d'un b-b-bain !
{15710}{15787}Joséphine t'aime | b-b-beaucoup.
{15830}{15884}Mais Joseph p-p-pas du tout !
{16155}{16260}Vos fleurs étaient si belles...
{16261}{16316}Moins belles que vous.
{16465}{16540}Pourrais-je... pourrais-je -
{16541}{16637}...vous emprunter | encore 1000 francs -
{16638}{16696}...jusqu'à ce que | mon argent arrive ?
{16720}{16754}Avec plaisir Fraulein.
{16835}{16880}Je vous les apporterai ce soir.
{16966}{17029}Oublie ça voyons !
{17032}{17067}C'était une blague.
{17068}{17128}Une blague, hein ?
{17130}{17201}"Je m'occuperai de toi | petite".. !
{17225}{17266}Et j'ai mordu à l'hameçon.. !
{17407}{17489}Reviens pas là-dessus !
{17697}{17800}Tu me laisses tomber ?
{17840}{17882}Non, c'est une blague !
{17890}{17934}Me laisse pas tomber -
{17937}{18009}...ou je t'arrangerai !
{18076}{18134}Pas ça. Je te l'avais donné.
{18165}{18223}Espèce de ....
{18260}{18310}Tu pourras toujours chialer -
{18310}{18360}...je te reprendrai pas !
{18360}{18415}Je perds mon temps | et mon argent -
{18415}{18469}...avec des garces comme toi.
{18504}{18559}Ton temps mais mon argent !
{18600}{18657}Fous le camp traînée !
{18960}{18994}Qu'est-ce que tu as | à me regarder ?
{19054}{19116}Je déménage. Parfaitement !
{19144}{19198}Tu as tout entendu, hein ?
{19241}{19312}C'est ça... Te gêne pas... Ris !
{19312}{19354}C'est drôle pas vrai ?
{19360}{19431}Les femmes sont drôles, | pas vrai ?
{19451}{19513}Toutes des traînées, pas vrai ?
{19528}{19591}Sauf quand on vit | à leurs crochets !
{19950}{20000}Non mais dis... | En voilà des façons.. !
{20035}{20104}C'est à Phroso que tu parles...
{20150}{20236}Pas à ces voyous | qui t'intéressent tant !
{20238}{20292}Pardonne-moi.
{20297}{20349}Fallait que je m'en prenne | à quelqu'un.
{20376}{20446}Les femmes.. ! Langues | de vipères, tricheuses...
{20446}{20502}Et ça piaille | quand on se rebiffe !
{20581}{20633}Pleure pas petite. Pleure pas.
{20700}{20741}Tout est de ma faute.
{20782}{20840}Et ce qui me fait râler | c'est -
{20840}{20904}...d'en avoir pincé | pour ce tas de muscles !
{20906}{20944}Tu as enfin compris, hein ?
{20944}{21050}Mieux vaut maintenant | que trop tard.
{21050}{21115}Quand personne | voudrait de toi.
{21115}{21166}Personne veut de moi.
{21170}{21240}Tu devrais être ravie | d'être libre !
{21250}{21280}Tu es pas si mal tu sais.
{21296}{21346}Arrange-toi, tu feras l'affaire.
{21360}{21387}Ta chance arrive...
{21400}{21450}Elle est passée oui.
{21451}{21510}Tu vas rester à pleurer | sur ton sort ?
{21510}{21580}Ça non ! | C'est pas mon genre !
{21698}{21787}En tout cas arrose | pas trop ta liberté.
{21787}{21855}Parce que ça, | ça arrange personne.
{21890}{21915}Compris.. ?
{21942}{21970}Compris.
{22125}{22158}Tu es un brave type.
{22177}{22200}Ça c'est vrai !
{22200}{22260}Si tu m'avais connu avant | mon opération...
{22478}{22526}Demain | c'est le grand soir Daisy ?
{22526}{22570}Oui, ma sœur se marie.
{22570}{22650}- Je ne tiens plus en place. | - Comme d'habitude !
{22664}{22722}Rosco est très chouette.
{22722}{22775}Elle l'appréciera -
{22775}{22811}...quand elle le | connaîtra mieux.
{22840}{22915}Au fait... Ferme les yeux | Violette.
{22930}{22960}Allons, ferme-les.
{23005}{23065}- J'ai fait quoi ? | - Tu as pincé Daisy.
{23088}{23138}Ça alors !
{23215}{23263}La voix de son maître...
{23295}{23387}Tu f-f-flirtais ! | J'aime p-p-pas ça !
{23387}{23427}Allez, viens.
{23427}{23479}Dépêchons. | On n'a pas le temps.
{23500}{23572}Tu f-f-flirtais avec ce clown !
{23592}{23640}Il me montrait un truc.
{23650}{23675}Toi tais-toi.
{23686}{23759}C'est ta sœur que | j'ép-p-pouse. P-pas toi !
{23782}{23821}J'ai tout vu.
{23821}{23860}Viens Daisy.
{23860}{23937}Pas question. Elle reste.
{23940}{23991}Non, on m'attend.
{24000}{24095}Toujours la même ex-ex-ex -
{24095}{24148}...le même alibi.. !
{24419}{24457}Où allez-vous ?
{24590}{24661}Vous ne regardez pas | souvent le spectacle.
{24695}{24735}Je vous ai vue.
{24750}{24797}Et... c'est tout ?
{24834}{24876}Il faut qu'on vous | fasse du charme ?
{25262}{25328}Entrez...
{25375}{25413}Servez-vous à boire.
{25578}{25617}Vous avez faim ?
{25634}{25663}Toujours.
{25970}{25997}Combien ?
{26013}{26087}Six suffiront.
{26225}{26262}Comment les voulez-vous ?
{26483}{26521}Vous êtes si fort !
{26524}{26573}Vous allez m'écrasez !
{26580}{26613}Ça te plait.
{26639}{26687}Je ne peux plus respirer !
{26989}{27015}Hé toi.. !
{27207}{27255}Ça t'apprendra à regarder !
{27453}{27520}Tu ne m'as pas écoutée...
{27613}{27659}Tu ne m'écoutes pas.
{27659}{27710}Si Frieda...Je t'assure.
{27720}{27754}Je disais quoi ?
{27780}{27852}Tu disais... qu'est-ce | que tu disais ?
{27873}{27969}Que tu devrais fumer | moins de cigares.
{27971}{28033}Tu étais très enroué ce soir.
{28055}{28107}Ne me dis pas ce que | j'ai à faire.
{28120}{28164}Quand je veux un cigare, | j'en fume un !
{28217}{28256}Tu n'as pas d'ordres | à me donner !
{28345}{28431}Depuis que nous | sommes fiancés -
{28431}{28516}...jamais tu ne m'avais | parlé comme ça.
{28630}{28681}Excuse-moi Friedchen.
{28715}{28747}Voici notre café.
{29007}{29060}Le macaque a fait venir | ça de Paris.
{29070}{29157}Nous nous débrouillons | très bien.
{29306}{29342}Mais je n'aime pas les fruits.
{29373}{29429}Pourtant ça te ferait du bien.
{29430}{29489}La prochaine fois | je réclame du champagne.
{29593}{29616}Qui est là.. ?
{29616}{29639}C'est Hans.
{29856}{29881}Qui.. ?
{29890}{29913}C'est Hans
{29940}{30020}Votre corbeille de fruits | est exquise.
{30025}{30060}Mais je...
{30075}{30130}Je suis dans mon bain.
{30145}{30184}Vous pouvez revenir | plus tard ?
{30398}{30460}Tu vas tout gâcher | s'il t'entend !
{30698}{30739}Vous ne chantez pas | aujourd'hui.
{30770}{30835}J'ai tellement de travail.
{30860}{30883}Comment va Hans ?
{30970}{31020}J'ai dit : "Comment va Hans ?"
{31147}{31224}Frieda, qu'est-ce qu'il y a ?
{31254}{31317}Rien... Seulement...
{31357}{31447}Cette Cléo... et mon Hans...
{31475}{31510}Je ne peux pas le dire...
{31510}{31552}Elle lui court toujours après ?
{31576}{31628}Elle est toujours | à lui sourire.
{31630}{31690}Si elle sourit | à certaines personnes -
{31690}{31750}...Cléo pourra | s'acheter un dentier !
{31755}{31841}Les femmes ont toujours | des soucis.
{31841}{31927}C'est comme ça, | on n'y peut rien.
{31940}{32011}Et elle est mauvaise avec moi !
{32035}{32103}Quand je peux entendre | elle lui dit :
{32126}{32194}"Merci pour vos fleurs | mon chéri."
{32214}{32258}"Merci mon chéri, | pour ci"...
{32269}{32318}"Merci mon chéri, | pour ça"...
{32335}{32399}Toujours quelque chose | qu'il lui a donné !
{32411}{32474}Rassurez-vous, | il ne l'aime pas...
{32501}{32540}Cette grande jument.. !
{32560}{32606}Mais elle le relance toujours.
{32622}{32658}C'est pour ça | que je m'inquiète.
{32760}{32792}Des collants roses -
{32804}{32850}...avec des paillettes.
{32850}{32896}Ça la mettra mieux en valeur.
{32920}{32964}Pas de collants.
{32982}{33001}Sans collants.
{33023}{33067}Du tissu transparent...
{33070}{33159}Qui laisse tout voir...
{33170}{33205}Pourquoi pas à poil.. ?
{33250}{33305}C'est ça, c'est ça...
{33305}{33360}A poil sur mon taureau !
{33360}{33442}Vous êtes de grossiers | personnages !
{33600}{33630}Qu'est-ce qu'il y a Fraulein.. ?
{33635}{33691}Je me suis froissé | l'épaule hier.
{33711}{33737}Voulez-vous la masser ?
{33822}{33895}Ça fait du bien...
{33920}{33977}Plus bas... plus bas...
{34141}{34210}C'est bon d'être massée.
{34212}{34254}Nos cartes Madame.
{34300}{34344}Pour des massages à domicile !
{34551}{34571}Tu sais...
{34595}{34638}J'ai rêvé de toi cette nuit.
{34695}{34757}Tu étais en maillot, debout sur un rocher...
{34774}{34807}Comme une statue.
{34824}{34896}Et le vent soufflait | dans tes cheveux.
{34907}{34969}Tu avais une de ces allures.
{34969}{35003}C'était superbe !
{35080}{35122}Tu es superbe.
{35173}{35197}C'est vrai ?
{35305}{35352}Tu as essayé mon truc ?
{35381}{35448}Oui et ils se sont esclaffés.. !
{35448}{35473}Je vais te montrer.
{35490}{35547}J'ai fait tout | ce que tu m'as dit.
{35555}{35585}Regarde Vénus.
{35669}{35726}Phroso, de quoi d'autre | tu as rêvé ?
{35735}{35809}De Paris. On était à l'Opéra.
{35809}{35883}Dans une loge. Sur notre 31.
{35883}{35920}Je portais quoi.. ?
{35925}{35992}Tout le monde me | regardait et disait :
{35992}{36059}"C'est Phroso, | le grand clown".. !
{36068}{36121}J'étais très gêné.
{36153}{36192}On parlait de moi ?
{36232}{36257}Qu'est-ce qu'on disait.. ?
{36265}{36335}Frappe-moi... Vas-y.
{36354}{36389}Sur la tête. Frappe.
{36660}{36680}Ça ne te plait pas ?
{36680}{36730}Tu ne trouve pas ça drôle ?
{36735}{36825}Le public, lui, | aura meilleur goût !
{37018}{37043}Quand ?
{37195}{37226}L'enfant de la femme | à barbe est né !
{37690}{37719}- Garçon ou fille ? | - Fille.
{37757}{37812}Elle aura une barbe | comme sa maman !
{37985}{38027}- Comment va le père ? | - Très bien.
{38035}{38065}-C'est quoi ? | - Une fille.
{38071}{38130}Tâche de faire mieux | la prochaine fois.
{38366}{38421}Ne te dispute plus | avec lui Violette.
{38437}{38487}S'il a quelque chose à dire | qu'il le dise.
{38495}{38544}Au lieu de b-b-bafouiller | des heures !
{38580}{38676}Je suis le m-maître ici !
{38681}{38717}Pas le mien.
{38775}{38840}Et je ne veux plus | voir ces voyous -
{38840}{38884}...que tu f-f-fréquentes !
{38920}{38970}Tais-toi et agrafe notre robe.
{38970}{39035}C'est pas la robe | que je vais agrafer...
{39035}{39070}C'est toi.. !
{39082}{39137}Et tu vas arrêter -
{39137}{39188}...de te cuiter | tous les soirs !
{39191}{39217}Tu crois ça ?
{39217}{39275}Je ne veux pas | que m-m-ma femme -
{39275}{39359}...se réveille avec | la gueule de bois !
{39367}{39393}Viens Daisy.
{39393}{39477}P-p-pas question ! | Daisy reste ici !
{39485}{39521}On m'attend.
{39542}{39650}Encore cette ex-ex-ex -
{39650}{39690}...et alibi !
{39867}{39919}Cléo n'est pas une des notres.
{39932}{40000}Nous ne sommes que des | curiosités pour elle.
{40020}{40104}Elle ne voit Hans | que pour ses cadeaux.
{40121}{40195}Qu'elle essaie de -
{40195}{40253}...faire du mal | à l'un de nous.. !
{40291}{40332}Hans ne se doute de rien.
{40335}{40390}Mais quand il comprendra...
{40613}{40664}Du coin de l'œil, j'ai vu -
{40664}{40715}...la patronne nous regarder.
{40735}{40774}Elle sait qu'elle tient | un bon numéro.
{40780}{40813}Un des meilleurs du monde.
{40870}{40909}Personne résiste | à nos personnalités.
{40910}{40949}On sait "vendre" | notre marchandise.
{40965}{41050}Partout où on passe.
{41074}{41134}Entre nous, dans ce cirque -
{41134}{41183}...on tue le temps.
{41210}{41250}Bientôt, à nous | les grands cirques !
{41339}{41395}Regarde notre nouveau | numéro demain.
{41606}{41671}Quelle jolie robe Schlitze !
{41671}{41735}Tu es bien belle ce soir !
{41819}{41879}Tu vas briser tous les cœurs.
{42000}{42060}A Paris, je t'achèterai | un beau chapeau -
{42060}{42119}...avec une longue plume.
{42337}{42413}Schlitze n'a pas | une jolie robe ?
{42424}{42474}A Paris, je lui | achèterai un chapeau -
{42474}{42520}...avec une longue plume.
{42534}{42584}Et à vous aussi -
{42584}{42642}...avec une plume | encore plus longue.
{42834}{42872}Qu'est-ce que tu as ?
{43005}{43061}Pardon Schlitze.
{43266}{43327}Tu l'as vu ? | Il était encore là ce soir.
{43340}{43382}Il te suit partout.
{43382}{43451}Si Eddie le voit | ça fera un drame.
{43458}{43497}Ce n'est pas ta faute.
{43497}{43576}Je te croyais couchée | Francès.
{43634}{43672}Tu as entendu | le public applaudir ?
{43694}{43736}On aurait dit le tonnerre.
{43755}{43779}Mais c'était pas ça.
{43800}{43850}C'était les Rollo qui triomphaient.
{43868}{43902}Comme partout ailleurs.
{43925}{43974}Ça en devient monotone.
{44000}{44051}Demain, regarde | notre numéro.
{44070}{44150}Doucement. | N'en renversez pas.
{44207}{44247}Regardez-le scintiller.
{44254}{44284}Comme vos yeux.
{44490}{44524}Délicieux.
{44647}{44720}Il vient des plus | grands vignobles.
{44745}{44786}Et il est pour moi ?
{44795}{44876}Pour la plus belle | femme du monde.
{45071}{45131}Salut. | Où tu étais passée ?
{45174}{45217}Tu es un drôle de type | Phroso.
{45250}{45290}Je sais jamais | où j'en suis avec toi.
{45290}{45342}Le public non plus. | Et ça plait.
{45343}{45395}Parce que je me sers | de ma cervelle.
{45409}{45478}Parce que je sais faire rire.
{45508}{45547}Avec moi c'est un art.
{45618}{45669}Pourquoi ce chapeau ? | Tu as froid ?
{45694}{45740}On devait sortir nous deux.
{45767}{45802}J'avais oublié.
{45822}{45885}J'ai ça à finir.
{45900}{45930}Dépêche-toi, alors.
{45945}{45987}J'ai mis ce que j'ai de mieux.
{45988}{46030}Impossible poupée.
{46150}{46195}Une autre fois, hein ?
{46255}{46310}Sois pas triste. | J'ai eu une idée et...
{46310}{46352}Faut que je la mette au point.
{46400}{46430}Marrant non ?
{46435}{46490}A pleurer de rire !
{46520}{46589}A la bonne heure...
{46969}{47012}Tu n'avais jamais fait ça.
{47031}{47073}Mais j'y pensais.
{47296}{47355}Depuis longtemps.
{47580}{47616}Tout va bien à présent ?
{47656}{47678}Tout va bien.
{47714}{47760}Je vous en prie, acceptez.
{47812}{47848}Vous voulez | me rendre heureux ?
{47875}{47940}Oui, mais je ne sais pas | quoi dire.
{47947}{47973}Dites seulement : "oui".
{48390}{48450}Tu as une bonne épouse. | Tu es heureux.
{48460}{48524}Oui, mais m-m-ma | belle sœur...
{48525}{48589}Elle p-p-passe | ses nuits à lire.
{48658}{48677}Ça c'est moche.
{49102}{49148}Cléo en est | aux d-d-demi-portions !
{49293}{49324}Vous êtes bien aimable.
{49332}{49390}Violette sera très heureuse.
{49390}{49425}Voici Rosco.
{49509}{49533}Rosco... M.Vadja.
{49545}{49588}Ench-ch-chanté.
{49605}{49644}Violette et lui vont se marier.
{49696}{49756}Vous viendrez nous voir | j'espère.
{49784}{49854}Vous aussi, rendez-nous | v-v-vis...
{49854}{49913}...venez nous voir.
{49938}{49972}Mais certainement.
{50171}{50183}Qui est là ?
{50339}{50375}C'est Frieda.
{50507}{50548}Je peux entrer ?
{51023}{51102}Je suis là et je ne sais | plus quoi dire...
{51110}{51162}...pour te faire comprendre.
{51223}{51279}Si tu savais | ce que j'éprouve -
{51280}{51336}...à venir te parler d'elle.
{51367}{51417}Frieda je suis désolé.
{51417}{51473}Je ne veux pas | te faire de peine.
{51567}{51617}Si tu pouvais être heureux -
{51618}{51668}...je n'aurais pas de peine.
{51687}{51722}Je suis heureux...
{51722}{51771}Mein Leben n'a jamais | été aussi heureux.
{51837}{51887}Tu le crois.
{51990}{52036}Si tu savais...
{52132}{52163}Je sais Hans.
{52198}{52263}Elle est belle, et moi | bien sûr je suis -
{52274}{52304}Tais-toi Hans.
{52314}{52403}Pour moi tu es un homme.
{52403}{52492}Pour elle tu es un jouet.
{52502}{52578}Tout le cirque rit de vous.
{52605}{52665}Qu'ils rient, les Schweine !
{52665}{52744}Ils ne peuvent pas | me faire de mal.
{52775}{52830}Ils m'en font à moi.
{52866}{52936}Frieda j'ai été lâche.
{52936}{53006}J'aurais dû te parler | dès le début.
{53006}{53058}Pardonne-moi.
{53086}{53146}Je te pardonne Hans.
{53155}{53259}C'est seulement | ton bonheur que je veux.
{53316}{53415}Tu ne t'inquiéteras plus ?
{53452}{53516}Non Hans.
{53660}{53712}Joli non ?
{53861}{53911}C'est du platine.
{53911}{53962}D'où ce macaque | sort-il l'argent ?
{54043}{54070}Pourquoi ? Ça t'inquiète ? | Ce serait nouveau.
{54084}{54144}Peu importe | d'où vient l'argent.
{54214}{54235}Ça peut valoir combien ?
{54266}{54313}On a eu 500 francs | du bracelet.
{54313}{54360}On aura au moins | quatre fois plus.
{54381}{54453}La prochaine fois | je réclame un renard argenté.
{54546}{54621}Le macaque a des vues | sur toi.
{54630}{54645}Jaloux.. !
{54664}{54750}Moi ? Je l'écraserai | comme une punaise !
{54806}{54876}C'est Hans. | Je vais m'en débarrasser.
{55218}{55233}Que voulez-vous ?
{55377}{55408}Vous parler de Hans.
{55500}{55525}J'écoute.
{55580}{55625}Quand il a le dos tourné -
{55625}{55671}...tout le monde rit.
{55671}{55717}Parce qu'il vous aime.
{55825}{55894}Vous vous moquez de lui...
{55894}{55963}Mais Hans ne le sait pas.
{55965}{56030}Quand il s'en apercevra -
{56030}{56093}...jamais plus | il ne sera heureux.
{56116}{56188}Pourquoi me moquerais-je  | de lui ?
{56204}{56252}Vous êtes grande... et si belle.
{56261}{56321}Et Hans est si petit...
{56323}{56363}Si mignon...
{56370}{56443}Peut-être que je vais l'épouser.
{56488}{56533}Si vous l'épousez -
{56533}{56589}...c'est de vous | qu'on se moquera.
{56597}{56663}Rien ne vaut la différence !
{56664}{56730}Cléopâtre, reine des airs -
{56730}{56796}...mariée à un nain !
{56839}{56863}Un nain.
{56875}{56904}Un nain...
{56934}{56988}Ce n'est pas Hans | qui vous intéresse.
{56988}{57018}C'est l'argent.
{57025}{57065}L'argent.
{57067}{57143}Comment avez-vous deviné ?
{57165}{57225}Il vous a parlé | de la fortune -
{57225}{57283}...dont il a hérité.
{57335}{57398}Il m'avait juré | de n'en parler -
{57399}{57462}...qu'après notre départ | du cirque.
{57509}{57553}Une fortune...
{57553}{57653}Et vous étiez | au courant, hein ?
{57653}{57753}Enfin, je ne peux pas | lui en vouloir.
{57812}{57908}Vous ne ferez pas ça...
{58385}{58415}Une fortune !
{58420}{58477}Ce macaque vaut | des millions je parie !
{58501}{58586}Une fortune... | tu te rends compte ?
{58635}{58685}Et je le tiens... comme ça !
{58700}{58776}Il avait bien su | garder son secret.
{58785}{58811}Je pourrais l'épouser.
{58860}{58920}Il m'épouserait.
{59112}{59177}Les nains ne sont pas forts.
{59225}{59263}Il pourrait tomber malade.
{59370}{59390}Ça pourrait se faire...
{59444}{59506}Lentement.
{59600}{59655}Le repas de noces
{60350}{60385}Allons mon trésor... buvons.
{60426}{60460}Une bonne grosse rasade.
{60605}{60683}Kou-kou, laisse la p-place | aux autres !
{60829}{60867}A vous p-p-professeur.
{60877}{60911}Une valse !
{61250}{61310}Fais mieux Volcan. | Grille-le.
{61594}{61647}Notre nuit de noces.. !
{61728}{61764}Passionnant !
{61780}{61868}J'ai tellement de chance !
{62005}{62060}C'est moi qui ai | de la chance.
{62060}{62103}Mon petit Hans...
{62131}{62208}Ma Cléo est heureuse.
{62350}{62430}Je suis heureuse | que je pourrais -
{62440}{62483}...t'embrasser -
{62483}{62526}...grande brute.. !
{62920}{63016}Mon petit monstre | aux yeux verts.. !
{63081}{63141}Mon mari est jaloux.
{63215}{63258} Il m'aime.
{63480}{63530}Allons mon petit amant.
{63546}{63576}Bois au bonheur -
{63576}{63655}...de ton épouse aimante.
{63860}{63921}Faisons-en une des nôtres !
{63921}{63982}Une coupe ! Une coupe !
{63986}{64079}Nous l'acceptons parmi nous.
{64120}{64179}Nous l'acceptons...
{64372}{64420}Tu vas être l'une des leurs -
{64420}{64468}...mon oiseau de paradis !
{66070}{66086}Vous.. !
{66197}{66225}Sales monstres !
{66225}{66312}Monstres ! Monstres ! | Allez vous-en !
{66397}{66447}Vous entendez ? | Foutez le camp !
{66611}{66652}Vermine.. !
{66685}{66752}Moi ! Une des vôtres.. !
{66753}{66918}Tu es un homme ou quoi ?
{66947}{66995}Tu me remplis de honte...
{66997}{67055}De honte.. !
{67101}{67161}C'est le bouquet !
{67207}{67287}Tu veux quoi ? | Que Maman joue avec toi ?
{67292}{67347}Au petit cheval peut-être ?
{67357}{67436}C'est ça, au petit cheval !
{67494}{67555}En selle microbe !
{67569}{67669}Maman sera le cheval !
{67774}{67817}Allez hop !
{68240}{68269}Pense plus à ça Hans.
{68290}{68337}Elle regrette... et moi aussi.
{68365}{68400}Elle avait bu je te dis.
{68415}{68490}On voulait seulement rigoler.
{68610}{68699}Je comprends... tout.
{68700}{68720}Tu comprends rien.
{68762}{68819}Y a rien entre Cléo et moi.
{68821}{68848}Tais-toi donc !
{68875}{68923}Tu as fait assez | de sottises ce soir !
{68939}{69015}Tu sais ce qu'il me reproche ?
{69028}{69078}Moi j'ai rien fait, | en tout cas.
{69133}{69190}Je ne te reproche rien Cléo.
{69235}{69291}Ni à vous Hercule.
{69325}{69402}Seulement à moi.
{69428}{69518}Ça c'est parlé ! Comme un homme !
{69532}{69552}Imbécile !
{69635}{69690}J'aurais toujours dû savoir -
{69707}{69763}...que tu te moquerais de moi.
{69798}{69869}Je préférerais tomber | de mon trapèze -
{69869}{69940}...et me tuer que | de te faire de la peine.
{69973}{69998}Comprends-le :
{70025}{70056}Ce n'était qu'une plaisanterie.
{70183}{70275}Notre mariage, | une plaisanterie.
{70350}{70412}C'est drôle en effet.
{70447}{70504}Hans le nain...
{70590}{70667}Hans l'idiot...
{70670}{70748}Le juge des divorces | rira bien.
{70780}{70844}Tout le monde rira... rira...
{70845}{70904}Rira... rira...
{71082}{71109}Tu lui en donnes trop.
{71158}{71190}Je sais ce que je fais.
{71225}{71268}Allez, ramasse-le.
{72075}{72115}Docteur, qu'est-ce que c'est ?
{72140}{72165}Qu'est-ce qui a causé ça ?
{72230}{72250}Le poison !
{72500}{72563}C'est un empoisonnement | à la ptomaïne.
{72680}{72710}Ai-je eu tort -
{72725}{72765}...de lui donner un vomitif ?
{72822}{72864}Vous l'avez sans doute sauvé.
{73130}{73203}Jamais il n'avait bu | comme ça.
{74037}{74076}Force Cléo à dire | au docteur -
{74076}{74115}...ce qu'elle a mis dans le vin !
{74220}{74250}Tu es folle !
{74250}{74324}Sinon j'irai trouver les flics.
{74370}{74411}Tu donnerais les tiens ?
{74411}{74452}Les miens comme tu dis -
{74452}{74529}...ils n'essayeraient pas | de tuer un nain !
{74543}{74563}Sale petite...
{74755}{74792}Tu as trop d'imagination.
{74838}{74870}Les flics n'en ont pas eux -
{74880}{74907}...à ce qu'on m'a dit.
{74973}{75038}M'oblige pas | à aller leur parler.
{76361}{76413}Il y a huit jours -
{76440}{76484}...que nous sommes mariés.
{76527}{76587}Huit jours que je t'ai dit -
{76590}{76660}...toutes ces choses.
{76660}{76710}Tais-toi.
{76735}{76787}Jamais je ne me pardonnerai.
{76845}{76913}J'ai oublié. | Rien ne compte -
{76915}{76988}...que ta guérison.
{77052}{77119}Tu es si bonne pour moi.
{77165}{77199}Je dois préparer | ton remède -
{77199}{77231}...ou je serai en retard.
{78935}{78986}Je reviens petit Hans.
{78995}{79036}Ne t'ennuie pas trop.
{79076}{79172}Je n'oublierai pas ce que | tu fais pour moi.
{79179}{79240}C'est ce que | je veux faire chéri.
{79321}{79349}Il faut que je me dépêche...
{79427}{79477}Laisse la porte ouverte | s'il te plait.
{80740}{80758}Cette nuit !
{80766}{80804}Ils seront prêts.
{80840}{80870}Vous viendrez ici.
{81101}{81210}Je dois préparer | ton remède chéri -
{81226}{81262}...ou je serai en retard.. !
{81348}{81393}Vermines !
{81425}{81444}Monstres !
{82075}{82105}Il attend.
{82518}{82542}Bientôt.
{83296}{83351}Tu imagines des choses...
{83351}{83410}J'ai entendu Hercule dire :
{83410}{83469}Cléo... Vénus en sait trop.
{83469}{83517}Hercule.. ? Vénus.. ?
{83940}{83996}Petit Hans, | il faut que tu dormes.
{83997}{84053}Tes amis devraient | s'en aller.
{84062}{84103}Je veux qu'ils restent.
{84111}{84195}Non. Ils reviendront demain.
{84205}{84291}Tu dois prendre | ton remède et dormir.
{84302}{84380}Allez vous-en... tous. | Vite, vite.
{84629}{84651}Que signifie.. ?
{84659}{84702}Donne-moi la fiole noire.
{85385}{85402}La fiole !
{85583}{85685}Pour mourir | il faut avaler le poison !
{86554}{86618}Va-t'en Vénus !
{86944}{86969}Va-t'en je te dis !
{86969}{86994}Va-t'en.. !
{89698}{89767}Comment elle est devenue | ainsi, mystère.
{89795}{89829}Vengeance | d'un amant jaloux.. ?
{89870}{89940}Code des monstres.. ?
{89981}{90015}La tempête.. ?
{90055}{90123}Quoi qu'il en soit, la voici...
{90462}{90500}Mais monsieur, ils insistent !
{90526}{90586}Depuis toutes ces années | je n'ai vu personne.
{90606}{90680}renvoie-les.
{90694}{90718}Oui Monsieur.
{90754}{90797}Je ne veux voir personne.
{90807}{90845}- Excusez-moi monsieur, | vous ne pouvez pas entrer.
{90846}{90869}- Je ne peux pas ?
{90870}{90908}- Non monsieur, j'ai des consignes. | - Bien..?
{90958}{90987}Tu feras bien une exception | mon vieux Hans
{90996}{91037}pour certains en tout cas.
{91071}{91114}pourquoi tu es venue ?
{91147}{91229}Je t'en prie, ne te fâche pas !
{91255}{91334}Vénus et Phroso | ont été gentils avec moi.
{91368}{91483}Va-t'en s'il te plaît. | Je ne veux voir personne.
{91553}{91625}mais tu as essayé | de les en empêcher !
{91670}{91716}Tu n'as pas voulu ça...
{91771}{91812}Ce n'était pas ta faute.
{91879}{91953}Ne pleurs pas...
{91991}{92075}Viens là mein liebchen. | Ne pleurez pas.
{92111}{92153}Ne pleurez pas, Hans.
{92170}{92193}Ne pleurez pas.
{92238}{92262}Je t'aime.
{92320}{92347}Je t'aime.
