{1}{1}29.970
{0}{180}PIRATES OF THE CARIBBEAN|English subtitlez by tHe.b0dY
{509}{629}Drink up me 'earties yo ho!
{635}{755}We kidnap and ravage and don't give a hoot.
{773}{893}Drink up me 'earties yo ho!
{914}{1034}Yo ho yo ho a pirate's life for me.
{1106}{1226}We extort, we pilfer, we filch and sack.|Drink up
{1268}{1388}Quiet, missy,|cursed pirates sail these waters.
{1391}{1436}You dont want to bring them|down on us now, do ya?
{1436}{1555}Mr. Gibbs that will do!|- She was singing about pirates.
{1579}{1750}Bad luck to be singing about pirates with us|mired in this unnatural fog. Mark my words.
{1750}{1807}Consider them marked.
{1852}{1894}On your way.
{1894}{1918}Aye, Lieutenant.
{1924}{1990}Its bad luck to have a woman on board, too,
{1993}{2050}even a miniature one.
{2074}{2182}I think itd be rather exciting|to meet a pirate.
{2191}{2245}Think again, Miss Swann.
{2275}{2365}Vile and dissolute creatures,|the lot of them.
{2365}{2455}I intend to see to that any man who sails|under a pirate flag or...
{2455}{2538}...wears a pirate brand|gets what he deserves.
{2553}{2640}A short drop and a sudden stop.
{2736}{2841}Lieutenant Norrington,|I appreciate your fervor.
{2841}{2958}But Im…Im concerned about the effect|this subject will have upon my daughter.
{2958}{3024}My apologies, Governor Swann.
{3024}{3144}- Actually, I find it all fascinating.|- Yes, thats what concerns me.
{3995}{4052}Look, a boy!|Theres a boy in the water!
{4133}{4190}Man overboard!
{4319}{4349}Haul him aboard!
{4624}{4681}Hes still breathing.
{4681}{4738}Mary, Mother of God!
{4951}{4984}What happened here?
{4999}{5101}Its most likely the powder magazine.|Merchant vessels run heavily armed.
{5215}{5257}A lot of good it did them.
{5272}{5359}Everyones thinking it.|Im just saying it...
{5359}{5476}Piratas!|- Theres no proof of that.
{5476}{5517}It was probably an accident.
{5589}{5631}Rouse the Captain immediately! .|- Hay, sir.
{5646}{5706}Heave to and take in sail,|launch the boats.
{5805}{5925}Elizabeth I want you to accompany the boy.|Hell be in your charge.
{5967}{6012}Take care of him.
{6599}{6626}Its ok.
{6650}{6698}My names Elizabeth Swann.
{6728}{6800}Will Turner.
{6812}{6872}Im watching over you, Will.
{7262}{7349}- Youre a pirate!|- Has he said anything?
{7367}{7463}His name is William Turner,|thats all I found out.
{7504}{7549}Take him below.
{9665}{9725}Elizabeth!
{9755}{9800}Are you alright?
{9842}{9959}Are you decent?|- Yes, yes!
{9989}{10109}Still abed at this hour?|Its a beautiful day.
{10217}{10274}I have a gift for you.
{10391}{10448}- Oh, its beautiful!|- Isnt it?.
{10504}{10546}May I inquire as to the occasion?.
{10546}{10666}Does a father need an occasion|to dote upon his daughter?
{10705}{10732}Go on.
{10837}{10894}Actually, I, uh...
{10924}{10996}I had hoped you might wear|it for the ceremony today.
{10996}{11026}The ceremony?
{11026}{11116}Captain Norringtons|promotion ceremony.
{11125}{11170}I knew it!
{11179}{11275}Commodore Norrington|hes about to become.
{11275}{11386}Fine gentleman, dont you think.|He fancies you?
{11428}{11488}Elizabeth?|Hows it coming?
{11529}{11586}Its difficult to say.
{11586}{11667}Im told its the latest|fashion in London.
{11667}{11745}Well, women in London mustve|learned not to breathe.
{11817}{11874}My lord, you have a visitor.
{12423}{12494}Ah, Mr. Turner,|good to see you again.
{12509}{12539}Good day, sir.
{12581}{12626}I have your order.
{12824}{12944}The blade is folded steel, thats gold|filigree laid into the handle.
{12983}{13046}If I may?
{13085}{13205}Perfectly balanced. The tang is|nearly the full width of the blade.
{13301}{13361}Impressive, very impressive.
{13433}{13534}Ah, now, Commodore Norrington is|going to be very pleased with this.
{13549}{13633}Do pass my compliments|on to your Master.
{13705}{13750}I shall.
{13762}{13879}A craftsman is always pleased|to hear his work is appreciated.
{13936}{14053}- Ah, Elizabeth, you look absolutely stunning.|- Will.
{14083}{14140}So good to see you!
{14152}{14269}- I had a dream about you last night.|- About me?
{14269}{14341}Elizabeth, is that entirely|proper for you to...?
{14341}{14392}About the day we met,|do you remember?
{14392}{14452}How could I forget, Miss Swann?
{14452}{14541}Will, how many times must|I ask you to call me Elizabeth?
{14541}{14643}At least once more,|Miss Swann, as always.
{14643}{14742}There, see.
{14742}{14760}At least the boy has|a sense of propriety.
{14760}{14832}Now, we really must be going.|Farewell.
{14871}{14946}Good day, Mr. Turner.
{14958}{15003}Come along.
{15090}{15132}Good day...
{15204}{15234}...Elizabeth.
{17943}{17970}What?
{17973}{18048}Hold up there, you.
{18072}{18177}Its a shilling to tie up your|boat at the dock.
{18246}{18306}And I shall need to|know your name.
{18363}{18480}What dye say to three shillings|and we forget the name?
{18593}{18650}Welcome to Port Royal, Mr. Smith.
{19750}{19813}Two paces front!
{19876}{19951}Right about turn!
{20020}{20068}Present...
{20068}{20110}...arms!
{20814}{20898}This dock is off limits to civilians.
{20898}{20985}Im terribly sorry, I didnt know.|If I see one...
{20985}{21045}...I shall inform you immediately.
{21129}{21246}Apparently theres some sort of a high toned|and fancy to do up at the fort, eh?
{21246}{21420}How could it be that two upstanding gentlemen|such as yourselves did not merit an invitation?
{21420}{21521}Someone has to make sure this|dock stays off limits to civilians.
{21521}{21641}Its a fine goal to be sure but|it seems to me that a...
{21650}{21770}a ship like that makes this one|here a bit superfluous, really.
{21794}{21908}Ah, the Dauntless is the power in these waters,|true enough, but theres no ship...
{21908}{21995}...that can match the|Interceptor for speed.
{21995}{22115}Ive heard of one, supposed to be|very fast, nigh un-catchable...
{22142}{22199}"The Black Pearl"
{22256}{22358}Well…theres no real ship that|can match the Interceptor.
{22403}{22516}- The Black Pearl is a real ship.|- No, no its not.
{22516}{22597}- Yes, it is, Ive seen it.|- Youve seen it?
{22597}{22693}- Yes.|- You havent seen it.
{22693}{22723}Yes, I have.
{22723}{22843}Youve seen a ship with black sails...
{22843}{22954}...thats crewed by the damned and|captained by a man so evil...
{22954}{23074}...that Hell itself spat him back?|- Ne.
{23104}{23146}Ne.
{23146}{23248}But I have seen a ship|with black sails.
{23248}{23368}Oh, and no ship thats not crewed by|the damned and captained by a man so evil...
{23377}{23437}...that Hell itself spat him|back out could possibly...
{23437}{23493}...have black sails therefore couldnt|possibly be any other ...
{23493}{23592}...ship than the Black Pearl.|Is that what you're saying?
{23622}{23673}Ne.
{23673}{23793}Like I said… theres no real ship|that can match the Interceptor
{23877}{23922}Hey!
{23943}{24012}You!
{24012}{24123}Get away from there!|You dont have permission to be aboard there, mate.
{24123}{24213}Im sorry, its just its such|a pretty boat  ship!
{24213}{24324}- Whats your name?|- Smith or...Smithy, if you like.
{24324}{24432}Whats your purpose in|Port Royal, Mr. Smith?
{24432}{24482}Yeah, and no lies!
{24482}{24650}Well, then, I confess, it is my intention|to commandeer one of these ships.
{24650}{24770}Pick up a crew in Tortuga,  raid, pillage, plunder|and otherwise pilfer my weasely black guts out.
{24791}{24848}I said no lies.
{24848}{24884}I think hes telling the truth.
{24884}{24992}If he were telling the truth,|he wouldnt have told us.
{24992}{25112}Unless, of course, he knew you wouldnt|believe the truth even if he told it to you.
{25421}{25451}May I have a moment?
{25738}{25858}You look lovely, Elizabeth.|- Yes?
{25861}{26110}I apologize if I seem forward but I...|must speak my mind
{26113}{26233}This promotion throws into sharp|relief that which I have...
{26269}{26419}...not yet achieved.|A marriage to a fine woman.
{26461}{26559}You have become a fine|woman, Elizabeth.
{26559}{26610}I cant breathe.
{26610}{26706}Yes, Im a bit nervous myself.
{26790}{26868}...and then they made me their chief.
{26919}{26970}Elizabeth?
{27039}{27090}Elizabeth!
{27150}{27210}The rocks!|Sir, its a miracle she missed them!
{27300}{27372}- Will you be saving her then?|- I cant swim.
{27432}{27506}Pearl of the Kings Navy you are.
{27506}{27551}Do not lose these.
{27989}{28046}What was that?
{29308}{29338}I got her.
{29350}{29440}- Not breathing.|- Move!
{29634}{29679}Never would have thought of that.
{29679}{29784}Clearly youve never been to Singapore.
{29934}{29994}Where did you get that?
{30039}{30069}On your feet.
{30159}{30204}Elizabeth.
{30219}{30324}- Are you alright?|- Yes, Im fine.
{30444}{30488}- Shoot him!|- Father!
{30506}{30623}Commodore, do you really|intend to kill my rescuer?
{30806}{30893}I believe thanks are in order.
{30998}{31073}Had a brush with the East India|Trading company, did we?
{31073}{31133}Pirate?
{31154}{31193}- Hang him.
{31193}{31313}Keep your guns on him, men.|Gillette, fetch some irons.
{31343}{31463}- Well, well... Jack Sparrow, isnt it?|- Captain Jack Sparrow, if you please, sir.
{31522}{31642}- Well, I dont see your ship...Captain.|- Im in the market as it were.
{31702}{31807}- He said hed come to commandeer one.|- Told ya he was telling the truth.
{31807}{31882}These are his, sir.
{31942}{32047}No additional shots nor powder...
{32077}{32167}A compass that doesnt point north...
{32287}{32377}And I half expected it|to be made of wood.
{32437}{32541}You are, without doubt, the worst|pirate Ive ever heard of.
{32553}{32631}But you have heard of me.
{32691}{32751}Commodore, I really must protest.
{32787}{32817}Carefully Lieutenant.
{32817}{32886}Pirate or not this man saved my life.
{32886}{33000}One good deed is not enough to redeem|a man of a lifetime of wickedness.
{33000}{33075}Though it seems enough|to condemn him.
{33075}{33126}Indeed.
{33141}{33186}Finally.
{33231}{33261}No, dont shoot!
{33261}{33381}I knew youd warm up to me.|Commodore Norrington, my effects, please...
{33381}{33435}...and my hat.
{33470}{33494}Commodore!
{33575}{33695}- Elizabeth, it is Elizabeth isnt it?|- Its Miss Swann.
{33695}{33815}Miss Swann, if youd be so kind.|Come, come, dear, we dont have all day.
{33890}{33950}Now if youd be very kind..
{34415}{34504}Easy on the goods, darling.
{34504}{34579}Youre despicable.
{34579}{34699}Sticks and stones, love. I saved your|life, you saved mine, were square.
{34741}{34819}Gentlemen, mlady.
{34819}{34915}you will always remember this as|the day that you almost caught...
{34915}{34984}...Capitan Jack Sparrow.
{35553}{35652}- Now, will you shoot him?|- Open fire!
{35862}{35904}On his heels!
{36467}{36587}Gillette, Mr. Sparrow has a dawn|appointment with the gallows...
{36587}{36653}...I would hate for him to miss it.
{39689}{39809}Right where I left you.
{39959}{39989}Not where I left you.
{40304}{40364}You're the one they're hunting.
{40394}{40439}The pirate.
{40678}{40753}Ah. Well, then it would be a shame to|put a black mark on your record.
{40753}{40798}So, if you'll excuse me...
{40915}{40984}Do you think this wise, boy...
{40984}{41053}...crossing blades with a pirate?
{41095}{41143}You threatened Miss Swann.
{41239}{41308}Only a little.
{41667}{41772}You know what youre doing,|Ill give you that. Excellent form...
{41787}{41862}...but hows your footwork?
{41862}{41982}If I step here...|Very good.
{42003}{42054}Now I step again.
{42207}{42246}Ta.
{42836}{42899}That is a wonderful trick.
{42911}{43031}Except once again you are|between me and my way out.
{43034}{43133}And now you have no weapon.
{43795}{43840}Who makes all these?
{43894}{43990}I do!|And I practice with them...
{44005}{44050}...three hours a day!
{44089}{44161}You need to find yourself a girl, mate.
{44389}{44502}Or, perhaps the reason you practice three|hours a day is that you already found one ...
{44502}{44622}...and are otherwise incapable|of wooing said strumpet.
{44637}{44691}You're not a eunuch, are you?
{44709}{44799}I practice three hours a day,|so that when I meet a pirate...
{44799}{44844}...I can kill it.
{47146}{47179}You cheated.
{47200}{47224}Pirate.
{47317}{47377}- Move away.|- No.
{47392}{47466}- Please, move.|- No!
{47466}{47526}I cannot just step aside|and let you escape.
{47616}{47688}This shot is not meant for you.
{47991}{48036}Move in!
{48126}{48291}Excellent work, Mr. Brown . Youve assisted|in the capture of a dangerous fugitive.
{48291}{48369}Just doing my civic duty, sir.
{48381}{48476}Well, I trust youll always remember|this as the day that Captain...
{48479}{48575}...Jack Sparrow almost escaped.
{48575}{48635}Take him away!
{48845}{48896}- Can you smell it.
{48899}{49019}- Nice juicy bone.|- Come here, boy.
{49031}{49151}You can keep doing that forever,|the dog is never going to move.
{49160}{49280}Oh, excuse us if we haven't resigned|ourselves to the gallows just yet.
{50463}{50583}- Has my daughter given you an answer yet?|- No, she hasnt.
{50634}{50697}Well, she has had a very trying day.
{50748}{50796}Ghastly weather, dont you think?
{50820}{50862}Bleak, very bleak.
{50919}{50943}Whats that?
{50988}{51012}Cannon fire!
{51084}{51132}Return fire!
{51138}{51258}I know those guns.
{51390}{51479}- Its the Pearl.|- Black Pearl?
{51566}{51686}Ive heard stories. Shes been preying on|ships and settlements for near ten years.
{51701}{51821}- Never leaves any survivors.|- No survivors?
{51848}{51926}Then where do the stories|come from, I wonder?
{54896}{54935}Goveror.
{54935}{55016}Barricade yourself in my office.
{55073}{55115}Thats an order!
{55675}{55699}Don`t...
{55711}{55753}Hello, chump.
{55888}{55912}Girl.
{56221}{56281}SMiss Swann, theyve come to kidnap you.
{56302}{56362}- What?|- Youre the Governors daughter.
{56475}{56565}They havent seen you. Hide and the|first chance you get, run to the fort.
{56877}{56907}Gotcha!
{57132}{57207}- Its hot! Its on me!|-Come on.
{58513}{58594}We know youre here, Poppet.
{58612}{58663}Poppet.
{58663}{58687}Come out.
{58726}{58786}We promise we wont hurt you.
{58885}{58930}We will find you, Poppet.
{58978}{59083}Youve got something of|ours and it calls to us.
{59278}{59338}The Gold calls to us...
{59389}{59448}Gold, gold.
{59607}{59631}Hello, Poppet.
{59688}{59745}- Parley|- What?
{59766}{59850}Parley. I invoke the right of parley.
{59874}{59967}According to the code of the brethren, set down|by the pirates Morgan and Bartholomew...
{59970}{60000}...you have to take me to your Captain.
{60012}{60072}I know the code.
{60078}{60144}If an adversary demands parley you|can do them no harm until ...
{60153}{60180}...the parley is complete.
{60189}{60225}To blazes with the code.
{60225}{60288}She wants to be taken to the Captain.
{60339}{60518}And shell go without a fuss.|We must honor the code.
{60845}{60893}Say goodbye!
{61025}{61049}Goodbye.
{61202}{61241}- Come on!|- Elizabeth.
{61525}{61570}Outta my way, scum!
{61954}{62053}My sympathies friend, youve|no manner of luck at all.
{62715}{62760}Come on, doggy.
{62766}{62856}Its just you and me now.|Its you and ol Jack.
{62862}{62931}Come on. Come on.
{62946}{63048}Good boy. Thats it.|Good boy, come on.
{63048}{63114}Bit closer, bit closer.
{63117}{63207}Thats it, thats it, doggy.
{63210}{63285}Come on you filthy, slimy, mangy cad.
{63351}{63420}No, no, no, no, no,|I didnt mean it. I didnt.
{63647}{63692}This aint the armory.
{63710}{63830}Well, well, well,|look what we have here Twigg?
{63857}{63923}Capitain Jack Sparrow.
{63962}{64157}Last time I saw you, you were all|alone on a godforsaken island.
{64157}{64277}Shrinking into the distance.|His fortunes arent improved much.
{64313}{64406}Worry about your own|fortunes, gentlemen.
{64412}{64531}The deepest circle of Hell is reserved|for betrayers and mutineers.
{64675}{64720}So there is a curse.
{64789}{64819}That's interestin.
{64828}{64885}You know nothing of Hell.
{65146}{65203}Thats very interesting.
{66279}{66321}I didnt know we were|takin on captives.
{66351}{66440}Shes invoked the right of parley|with Captain Barbossa.
{66449}{66551}- I am here to negotiate...|- You will speak when spoken to.
{66590}{66710}And yell not lay a hand on those|under the protection of parley.
{66734}{66785}Aye, sir.
{66863}{66893}My apologies, Miss.
{66953}{67073}Captain Barbossa, I am here to negotiate|the cessation of hostilities l ...
{67088}{67130}...against Port Royal.
{67145}{67265}There are a lot of long words in there, Miss,|were naught but humble pirates.
{67307}{67424}- What is it that you want?|- I want you to leave and never come back.
{67495}{67555}Im disinclined to acquiesce to your request...
{67636}{67681}...means no.
{67738}{67798}Very well.
{67843}{67867}I'll drop it.
{68026}{68137}Me holds are burstin' with swag and|that bit of shine matters to us?
{68176}{68281}- Why?|- Its what youve been searching for.
{68323}{68425}I recognized the ship. I saw it eight years|ago on the crossing from England.
{68436}{68475}Did ya now?
{68559}{68616}Fine.
{68619}{68739}Well, I suppose if it is worthless then|theres no point in me keeping it.
{69096}{69162}You have a name, Missy?
{69189}{69267}Elizabeth... Turner
{69309}{69369}Im a maid in the|Governors household.
{69464}{69494}Miss Turner.
{69581}{69605}Bootstrap.
{69740}{69815}And how does a maid come to|own a trinket such as that?
{69818}{69887}Family heirloom, perhaps?
{69926}{70016}I didnt steal it if thats what you mean.
{70016}{70136}Very well, you hand it over and well put your|town to our rudder and never return.
{70567}{70606}Our bargain?
{70693}{70768}Still the guns and stowem, ...The men.
{70792}{70912}Wait! You have to take me to shore.|According to the code of the order of the brethren...
{70912}{71029}First, your return to shore was|not part of our negotiations...
{71029}{71098}...nor our agreement so|I must do nothing.
{71098}{71218}And secondly, you must be a pirate for|the pirates code to apply and youre not
{71218}{71380}And thirdly, the code is more what you'd|call "guidelines" than actual rules.
{71380}{71490}Welcome aboard the Black Pearl,|Miss Turner.
{72126}{72183}Theyve taken her.|Theyve taken Elizabeth.
{72201}{72270}Mr. Murtogg, remove this man.
{72270}{72363}We have to hunt them down,|we must save her.
{72363}{72420}And where do you propose we start?
{72443}{72557}If you have any information concerning|my daughter, please, share it.
{72635}{72755}That Jack Sparrow.|He talked about the Black Pearl.
{72758}{72827}Mentioned it, is more what he did.
{72869}{72896}Ask him where it is.
{72902}{72965}Make a deal with him|he could lead us to it.
{72965}{73019}No...
{73019}{73112}the pirates who invaded this Fort left|Sparrow locked in his cell ergo....
{73112}{73178}...they are not his allies.
{73178}{73262}Governor, we will establish|their most likely course...
{73274}{73325}Thats not good enough!
{73355}{73474}Mr. Turner, you are not a military|man, you are not a sailor.
{73543}{73663}You are a blacksmith and this is|not the moment for rash actions.
{73750}{73825}Do not make the mistake of thinking|you are the only man here...
{73828}{73870}...who cares for Elizabeth.
{74230}{74251}You!
{74251}{74302}- Sparrow.|- Aye.
{74302}{74368}You are familiar with that ship,|the Black Pearl?
{74413}{74469}- Ive heard of it.|- Where does it make berth?
{74478}{74577}Where does it make berth?|Have you not heard the stories?
{74661}{74868}Captain Barbossa and his crew of miscreants|sailed from the dreaded Isla de Muerta.
{74868}{74988}Its an island that cannot be found except|by those who already know where it is.
{75033}{75072}The ships real enough.
{75102}{75186}Therefore its anchorage must be|a real place. Where is it?
{75213}{75312}- Why ask me?|- Because youre a pirate.
{75318}{75390}And you want to turn pirate|yourself, is that it?
{75437}{75464}Never.
{75578}{75677}- They took Miss Swann .|- Oh, so it is that youve found a girl.
{75677}{75743}I see.
{75743}{75914}Well, if youre intending to brave all, hasten|to her rescue and so win fair ladys heart...
{75914}{76034}...youll have to do it alone, mate.|I see no profit in it for me.
{76067}{76163}- I can get you out of here.|- Hows that? The keys run off.
{76169}{76274}I helped build these cells.|These are half pin-barrel hinges.
{76331}{76412}With the right leverage and|a proper application of strength...
{76465}{76498}...the door will lift free.
{76576}{76672}- Whats your name?|- Will Turner.
{76714}{76774}That will be short for William,|I imagine.
{76774}{76894}Good, strong name. No doubt,|named for your father, aye.
{76954}{76990}Yes.
{77071}{77149}Aha. Well, Mr. Turner,|Ive changed me mind.
{77173}{77257}If you spring me from this cell,|I swear on pain of death...
{77257}{77377}...I shall take you to the Black|Pearl and your bonny lass?
{77377}{77496}- Do we have an accord?
{77556}{77628}- Agreed.|- Agreed, get me out.
{77751}{77787}Hurry, someone will|have heard that.
{77793}{77841}Not without my effects.
{78048}{78084}Were going to steal a ship?
{78162}{78180}That ship?
{78180}{78300}Commandeer.|Were going to commandeer that ship.
{78303}{78339}Nautical term.
{78375}{78422}One question about your business boy,|or theres no use going.
{78473}{78593}This girl, how far are you|willing to go to save her?
{78608}{78671}- Id die for her.|- Oh, good.
{78680}{78722}No worries, then.
{79322}{79391}This is either madness or brilliance.
{79415}{79513}Its remarkable how often|those two traits coincide.
{80413}{80514}Everyone stay calm,|we are taking over the ship.
{80514}{80580}Aye, avast!
{80679}{80736}This ship cannot be crewed by two men.
{80772}{80814}You'll never make it out of the bay.
{80850}{80883}Son.
{80907}{81027}Im Captain Jack Sparrow, savvy?
