{1}{1}12.500
{40}{68}Forever.
{60}{125}To the Butcher!
{205}{233}Why don't you get out of here, Johnny?
{266}{284}Go on. Go!
{490}{535}Is there anyone in the Five Points|you haven't fucked?
{517}{526}Yes!
{531}{536}You!
{673}{696}Belt down!
{833}{860}Try it and I'll bite ya.
{862}{889}You were gonna bite me.
{888}{915}I dont think you want me.
{901}{927}Find out.
{1314}{1331}Oh, Jenny!
{1861}{1886}I can't sleep.
{1956}{2049}I hope you don't mind us|laying here, sir?
{2015}{2069}Whatever takes your fancy,|young friend.
{2178}{2216}Is your shoulder keeping you up?
{2207}{2252}I don't sleep too much.
{2247}{2309}I sleep with one eye open. I only|got one eye.
{2353}{2392}How old are you Amsterdam?
{2444}{2536}Not too sure. Never did|figure it.
{2512}{2557}I'm 47.
{2561}{2593}47 years old.
{2634}{2718}You know how I stayed alive|this long? All these years.
{2709}{2729}Fear!
{2752}{2805}The spectacle of fearsome acts.
{2803}{2873}Somebody steals from me, I cut|off his hands.
{2838}{2908}He offends me, I cut out his tongue.
{2880}{2985}He rises against me, I cut off his|head, stick it on a pike!
{2948}{3022}Raise it high up, so all in the|streets can see.
{3011}{3061}That's what preserves the order|of things.
{3093}{3110}Fear.
{3146}{3218}That one tonight. Who was he?
{3213}{3304}A nobody. A coward.
{3294}{3367}What an end that|would have been.
{3353}{3437}I killed the last honourable man|15 years ago.
{3416}{3440}Since then....
{3468}{3504}You've seen his portrait downstairs?
{3546}{3586}Has your mouth been glued up with juice?
{3566}{3599}I asked you a question!
{3582}{3618}I said I've seen it, sir.
{3675}{3743}You got a murderous rage in you.|I like it.
{3716}{3791}So much life boiling up in you.|That's good!
{3807}{3887}The priest and me lived by the|same principles.
{3887}{3938}Only faith divided us.
{3955}{3991}He gave me this you know?
{4045}{4100}That was the finest beating I|ever took.
{4092}{4204}My face was pulp. My guts pierced.|My ribs all messed up.
{4212}{4252}When he came to finish me...
{4295}{4334}...I couldn't look him in the eye.
{4399}{4437}He spared me because...
{4437}{4482}....he wanted me to live in shame.
{4460}{4494}This was a great man.
{4520}{4546}A great man.
{4581}{4632}So I cut out the eye that|looked away.
{4653}{4702}Sent it to him wrapped in|blue paper.
{4696}{4757}I would've cut them both out if I|could afford being blind.
{4761}{4811}I rose up again with a full heart...
{4800}{4847}...and buried him in his own blood.
{4944}{4960}Well done!
{5002}{5063}He was the only man I killed|worth remembering.
{5185}{5221}I never had a son.
{5314}{5361}Civilisation is crumbling.
{5568}{5594}God bless you!
{5964}{6000}If you've got anything to say...
{6005}{6041}...now is the time to say it.
{6042}{6070}Who is he to you, Jenny?
{6141}{6176}I was 12 years old.
{6175}{6237}My mother was dead. I was living|in a doorway.
{6247}{6401}He took me in. Took care of me in|his own way.
{6396}{6436}After they cut out the baby...
{6461}{6521}He doesn't fancy girls that|scarred up.
{6584}{6665}You should know, in your own mind...
{6653}{6725}...that he never laid a hand on me|till I asked him too.
{6971}{7001}Who are you?
{7009}{7043}Who are you?
{7958}{8131}Gentlemen, you are most welcome to|this palace of enchantment...
{8051}{8249}...with visions to rival the tales of|Sheherazade and the Arabian Nights!
{8440}{8489}Flex your head to the teutonic beauty!
{8472}{8534}Feast you eyes on the magnificent blue...
{8517}{8549}...of these creatures.
{8541}{8618}Gentlemen, you see our caged birds well!
{8588}{8651}How would you like to make them sing?
{8626}{8748}They could be singing for you.
{8773}{8860}May God put the spirit of the|holy steel in my spine...
{8833}{8902}...and the love of the blessed|Virgin in my heart.
{8909}{8930}Amen.
{8977}{9052}Easy now. What did you say?
{9025}{9067}He's not who he says he is.
{9069}{9106}He's not who he says he is?
{9146}{9199}Count you blessings he considers|you a friend!
{9199}{9299}The only thing he considers every day|and night is how to kill you!
{9283}{9345}Those eyes want me to take|them out for you!
{9334}{9388}I'll bury it up you fundunem where|it belongs!
{9370}{9426}I can read right through them!|They're empty...
{9398}{9423}His name is Vallon.
{9444}{9470}Don't do it Bill!
{9464}{9489}His name is Vallon!
{9871}{9919}Curious people these celestials.
{9921}{9959}You know why they use short|sleeves?
{9947}{9996}So everyone can see he's got|nothing stashed.
{9979}{10026}I hope it doesn't become a fashion.
{10092}{10104}Johnny?
{10561}{10577}Get up!
{10762}{10883}Ladies and gentlemen, if I may have|your kind attention.
{10822}{10880}As some of you have surely|noticed...
{10857}{10945}...our friend and benifactor, Mr Cutting...
{10906}{11047}..is tonight wearing a waistcoat|of certain distinction!
{11034}{11119}May we appeal to him, to favour us...
{11077}{11135}...with another exciting exhibition.
{11112}{11260}Of skill. Courage. Daring and drama!
{11427}{11448}What's gonna happen?
{11783}{11810}The spider's kiss!
{11840}{11863}The wheel of death!
{11859}{11884}William Tell!
{11878}{11891}The butterfly!
{11902}{11924}The spider's kiss!
{11920}{11957}The Butcher's apprentice!
{11948}{11974}The Butcher's apprentice!
{11964}{12018}A command performance!
{12018}{12040}Where have you been?
{12033}{12087}A command performance indeed.
{12066}{12089}I want you to get out of here!
{12085}{12160}And for this, I must beg the|indulgence...
{12122}{12144}...of my former...
{12133}{12188}... assistent in matters of impailment...
{12176}{12231}...the Butcher's original apprentice.
{12227}{12256}What do you say, Jen?
{12246}{12300}One more time for the|sweet souvenir.
{12290}{12301}Come on!
{12423}{12457}Don't do it!
{12590}{12616}She'll be alright.
{12648}{12669}Remember this?
{12661}{12672}Of course!
{12790}{12884}You may feel more comfortable without|that garment, Miss Everdeane!
{12864}{12912}You'll have to filch me a|new one, Bill!
{13062}{13109}Anything in your pockets tonight?
{13094}{13139}I ain't started working yet.
{13160}{13212}What about that locket I| gave you?
{13378}{13434}Apologies my dear. Pick it up.
{13475}{13510}Whoopsie daisy!
{13524}{13561}Now its good and broke!
{13562}{13612}I can't seem to get anything|right tonight.
{13686}{13755}You got the sand to give 'm a|grand finale?
{13832}{13884}Maybe when you're aiming a|little straighter.
{13988}{14026}Enough of this heathen music.
{14019}{14066}Get rid of these goddamn monkeys.
{14045}{14067}Strike up boys!
{14076}{14140}This is a night for Americans!
{14210}{14222}Jenny!
{14899}{14922}Hats off!
{15000}{15094}We hold in our hearts the memory|of our fallen brothers...
{15061}{15118}...whose blood stains the very streets...
{15090}{15121}...we walk today.
{15125}{15250}Also on this night, we pay tribute|to the leader of our enemies.
{15213}{15254}An honourable man...
{15246}{15341}...who crossed over bravely.|Fighting for what he believed in.
{15382}{15472}To defeat my enemy, I extinguish|his life...
{15438}{15502}... and consume him as I consume|these flames.
{15502}{15547}In honour of Priest Vallon.
{15554}{15577}In honour of Priest Vallon!
{15631}{15667}That's a wound !
{15766}{15853}I want you all to meet the son of|Priest Vallon.
{15824}{15865}I took him under my wing...
{15858}{15896}...and see how I'm repaid.
{15886}{15955}He saved my life one day so he|could kill me the next...
{15920}{15955}...like a sneak thief.
{15943}{15980}Instead of fighting like a man.
{15984}{16078}A base defiler. Unworthy of|a noble name.
{16193}{16239}That'll do Mcgloin.|Spread him out.
{16245}{16326}I hate blackies. You..you get to watch.
{16366}{16403}This is fresh meat!
{16415}{16464}We need to tenderise this meat|a bit.
{16457}{16533}Alright, lets kiss goodnight to|that pretty face of yours!
{16626}{16650}No.......!
{16666}{16766}What'll it be then. Rib or chop.|Loin or shank.
{16716}{16727}The liver!
{16721}{16733}The spleen!
{16743}{16756}The kidney!
{16835}{16847}The lung!
{16845}{16858}The liver!
{16863}{16874}The tongue!
{16898}{16931}The heart! The heart!
{16915}{16943}The heart?
{16933}{16971}This boy has no heart.
{16952}{17011}Then kill him!
{17047}{17087}He ain't earned the death!
{17072}{17128}He ain't earned the death of|my hands!
{17124}{17195}He'll walk amongst you marked|with shame.
{17159}{17272}A freak. Worthy of Barnum's|museum of wonders.
{17228}{17316}God's only man, speared by|the Butcher.
{17744}{17816}Here. Here. This way.
{17780}{17800}Come on.
{18352}{18390}I want to show you something.
{18442}{18485}My mother's bones share this|grave.
{18500}{18572}I've saved 20 cents out of every|dollar I've ever earned since ....
{18536}{18561}...I was thirteen.
{18583}{18624}That's 215 dollars.
{18618}{18658}For bludgeoning and the rest.
{18697}{18754}This is what I wanted to show you.
{18749}{18813}This is where we're going to go,|as soon as you get better....
{18787}{18872}...San Fransisco, California.
{18862}{18908}You can have anything you want|out there.
{18906}{18982}These men are pulling gold right|out of the river.
{18950}{18978}With their own hands.
{18992}{19078}We're here and need to get there.
{19059}{19085}Start here.
{19085}{19148}Go down 'round here.
{19151}{19182}Up to San Francisco.
{19200}{19230}The shortest way to go.
{19237}{19265}Will you go with me?
{19559}{19623}No need to fire that, miss.|Or even aim it.
{19611}{19666}An audience with yor mangled|friend is all I want.
{19842}{19881}I've 44 notches on my club.
{19888}{19918}Do you know what they are for?
{19938}{19981}To remind me of what I owe God|when I die.
{20057}{20100}My father was killed in battle too.
{20099}{20141}In Ireland, in the streets.
{20156}{20202}Fighting those who were taking|their privilege.
{20189}{20226}What only could be got and held...
{20208}{20251}...by the decimation of a race.
{20250}{20303}That war is a thousand years old|and more.
{20300}{20342}We never expected it to follow|us here.
{20356}{20371}It didn't.
{20382}{20418}It was waiting for us when|we landed.
{20458}{20536}Your father tried to carve out a|corner in this country for his tribe.
{20533}{20571}That was him. That was his Dead Rabbits.
{20602}{20656}I often wondered, if he'd lived a|bit longer...
{20655}{20696}...would he have wanted it to|be more.
{20822}{20874}Why did you rifle through his|pockets then?
{21067}{21097}For safekeeping.
{21132}{21163}I thought maybe you could do|with it.
{21424}{21464}Blood stays on the blade.
{22374}{22418}That's a sorry looking pelt.
{22456}{22533}And it's been so nice and quiet|for the last three months.
{22530}{22602}Tell me, this charge. Does it sit|on easy with you?
{22588}{22696}No. Not uneasy , Bill.
{22662}{22701}I wouldn't say that.
{22716}{22820}But.....my allegiance is|to the law.
{22792}{22840}I'm paid to uphold the law.
{23013}{23070}What in heaven's name are you|talking about?
{23105}{23211}You may have misgivings, but don't go believing|that, Jack. That way lies damnation.
{23210}{23254}I'm in no danger of|damnation, Bill.
{23381}{23409}Here's the thing.
{23422}{23499}I don't give a fuck about your moral conflicts...
{23461}{23496}..you meatheaded shit sack.
{23510}{23547}That's more or less the thing.
{23559}{23624}I want you to go out there. You|and nobody else.
{23600}{23627}None of your little minions.
{23613}{23652}I want you to go out there...
{23654}{23683}...and I want you...
{23690}{23771}...to punish, the person...
{23739}{23782}...who's responsible...
{23796}{23883}...for murdering this poor|little rabbit.
{23923}{23953}Is that understood?
{23995}{24013}Right!
{24031}{24096}Help yourself to some decent meat|on the way out.
{24520}{24532}Damn it!
{24560}{24587}Is that you, boy?
{24601}{24654}I didn't mean nothing by that shot|you know?
{24647}{24680}You scared me is all.
{24706}{24758}You know I'd never do you harm.
{24751}{24784}Come out now, lad.
{24806}{24847}Remember your father and me?
{24876}{24942}Are you to young to remember your Uncle Jack?
{24941}{24984}The times we had.
{25043}{25076}You know I won't hurt you.
{25457}{25487}This is bad for everybody.
{25472}{25514}What's next, dead politicians?
{25521}{25573}I could spare half a dozen|of you...
{25555}{25589}...easier than I can spare him.
{25592}{25664}Still, I think it shows dash.
{25640}{25709}Give the boy some time, we'll|settle with a good dust up.
{26065}{26088}The lads!
{26208}{26275}There are more of us coming off|the ships each day.
{26256}{26307}I heard 15,000 Irish a week.
{26313}{26351}And we're afraid of the Natives!
{26367}{26395}Get all of us together...
{26381}{26413}....we ain't got a gang..
{26402}{26426}...we got an army.
{26421}{26525}And all we need is a spark. One|spark, to wake us all up.
{26690}{26722}It was me who played you false.
{26739}{26772}I'd take it back if I could.
{26755}{26784}Take it back?
{26825}{26861}Johnny, I ought to kill you!
{27021}{27072}Get out of the Points and|don't come back.
{27152}{27177}Where are you going, boil?
{27191}{27207}Come along.
{27213}{27227}Come on.
{27262}{27305}Tell us John, what's the trouble?
{27308}{27336}No trouble, Bill.
{27365}{27405}Still hiding out with| your friends?
{27433}{27521}No, I'm not with them, Bill.
{27492}{27548}I'm with you, with the Natives.
{27584}{27662}You always were a Native, as far|as I'm interested, John.
{27661}{27707}Till you became a stag.
{27740}{27781}You tell me you're a Native?
{27760}{27791}Do you want to know what|a Native is?
{27807}{27938}A Native is a man, who's|willing to give his life...
{27886}{27919}...for his country.
{27928}{27970}Like my father done.
{27995}{28058}Are you willing to do that,| my young friend?
{28147}{28187}John? Johnny?
{28278}{28294}Johnny?
{28411}{28428}I'll get you off.
{28587}{28623}It hurts too much.
{28692}{28717}Just kill me.
{28773}{28804}Just kill me.
{28821}{28869}Please. Please.
{28927}{28983}Please. Please.
{29004}{29019}Please.
{29077}{29105}I'm sorry, Johnny.
{29297}{29348}Oh, Mary mother of God, pray|for us sinners...
{29323}{29370}...on the day of our death...amen.
{29372}{29404}Rest in peace, Ma.
{29432}{29460}What are you doing here, boil?
{29538}{29590}What's that nigger doing in| this church?
{29628}{29679}What's a Dead Rabbit doing with|the Natives,huh?
{29654}{29694}No niggers among the Natives.
{29674}{29710}Niggers as robbers is|one thing...
{29692}{29751}...but niggers in a church,|that's something else!
{29730}{29763}You run with the Natives, you go|pray with the Natives!
{29747}{29808}You're going to wind up on a stake|like your man did!
{29787}{29801}McGloin?
{29810}{29891}Father! Jezus, do you know there's|a nigger in your church?
{30080}{30109}Jezus!
{30380}{30408}The earth turns...
{30418}{30460}...but we don't feel it move.
{30482}{30522}And one night you look up...
{30528}{30636}...one spark and the skie's on fire.
{30727}{30767}It's a touching spectacle.
{30779}{30833}We'll come back when you're|ready for us.
{30895}{30953}The past is the torch that|lights our way.
{30943}{30989}Where our fathers have shown|us the path.
{30980}{31010}We shall follow.
{31029}{31105}Our faith is the weapon most|feared by our enemies...
{31082}{31133}...for thereby shall we lift our|people up...
{31107}{31157}...against those who will|destroy us.
{31145}{31250}Our name is called the Dead Rabbits,|to remind all of our suffering...
{31205}{31261}...and as a call to those who|suffer still...
{31233}{31267}...to join our ranks.
{31256}{31370}However so far they may have strayed|from our common home across the sea.
{31313}{31409}For with great numbers, must come|great strength.
{31371}{31414}For the salvation of our people.
{31414}{31436}We don't want your business.
{31425}{31445}How many other men live here?
{31441}{31462}You all have to register.
{31451}{31494}You can't force me to join|no army.
{31477}{31498}Have you got 300 dollars?
{31488}{31501}Of course not!
{31494}{31528}Who the hell's got 300 dollars?
{31511}{31583}If you are drafted, release from militairy| service can only be secured...
{31552}{31612}...for 300 dollars, according to|the conscription act.
{31582}{31596}300 Dollars?
{31589}{31619}Otherwise you have to serve!
{31604}{31639}Who the hell's got 300 dollars?
{31621}{31639}You have to serve, sir!
{31630}{31645}You tell me!
{31661}{31675}Boys!
{31693}{31747}I was born here, sir. You|immigrated here!
{31742}{31803}Sweet jezus. War does terrible|things to men.
{31781}{31819}Get back up town, where you|belong!
{31800}{31867}300 dollars. It's another rich|man's war!
{31855}{31904}Sir, I request an audience|with this man.
{31912}{31955}Don't they speak English in|New York anymore!
{31940}{31969}Don't understand.
{31954}{31979}You do speak English!
{31988}{32096}I wonder if miss Everdeane can angle| her rifle in another direction?
{32105}{32196}I wonder Mr. Vallon, if you understand|the value of this sort of publicity?
{32188}{32289}The Archbishop himself, shoulder to shoulder|with half the Irish in the Five Points.
{32263}{32323}I'm offering my boy, to form an|alliance with you...
{32293}{32358}...against Bill Cutting and his|slate of Native candidates.
{32338}{32406}I'll negotiate a handsome fee, for|every Irish vote...
{32372}{32434}...you send Tammany's way, in the|coming elections.
{32433}{32481}I need a new friend in the Five|Points, son.
{32509}{32542}I'd like that friend to| be you.
{32578}{32619}Now just a moment, Mr. Tweed.
{32611}{32657}Suppose we do get you those votes.
{32677}{32736}Would you back an Irish candidate|of my chosing..
{32706}{32723}I don't think so.
{32715}{32755}What if we get you all the|Irish votes?
{32735}{32822}Mr. Vallon, that will only happen|in the reign of Queen Dick!
{32814}{32834}Beg your pardon?
{32824}{32856}That means it will never happen.
{32840}{32905}Now I might be persuaded to back|an Irish candidate...
{32872}{32899}...for, let's say alderman.
{32886}{32895}Alderman?
{32896}{32944}We've already got an Irish|alderman.
{32920}{32942}So we have, that's why....
{32931}{32964}What's bigger than an alderman?
{32980}{32997}Sheriff!
{32999}{33017}Sheriff!
{33012}{33088}Alright, Mr Tweed, you back an|Irishman for sheriff...
{33050}{33093}...of the city and county of|New York...
{33072}{33120}...and we'll get him elected.
{33096}{33124}I love the Irish, son...
{33110}{33164}..but higher than alderman you|shall never climb.
{33137}{33156}Why not?
{33154}{33222}For one thing, no man living can|consolidate the Irish vote.
{33188}{33199}I can!
{33193}{33232}And for another, I mean no|offence...
{33221}{33257}...no one's yet found an Irish|candidate...
{33239}{33276}...for sheriff worth voting for.
{33301}{33313}Monk!
{33329}{33339}Here.
{33400}{33458}Got me looking as sober as me own|grandfather!
{33429}{33462}He was a great man, I'm sure.
{33451}{33492}He was a drunken bastard.
{33509}{33537}Can I say what I want?
{33544}{33575}That's why I wanted you.
{33574}{33644}Our elected representatives are a|gang of thieves!
{33609}{33649}Who swear to better our lot...
{33635}{33680}...while dipping their hands deep|into our pockets.
{33664}{33777}I stand shoulder to shoulder with|community leaders like Bill Cutting...
{33720}{33818}....against any, an all in roads in|our democracy.
{33769}{33811}I'll see to it, that no one|takes away...
{33795}{33847}... what you earned by pluck and application.
{33821}{33877}To invading hordes of Hibernians.
{33848}{33892}Go to the polls and put|your mark...
{33874}{33923}... next to the name Walter McGinn.
{33899}{33963}Against the potatoes weeders, like|them over there...
{33938}{33972}...thieving our jobs.
{33955}{34019}Why should so many Irish die down|south...
{33987}{34014}...when the first war to win...
{34000}{34051}...is not down in Dixie, but|right here...
{34026}{34051}...in these streets!
{34071}{34120} Who's the finest streetfighter in|the Five Points?
{34100}{34123}Monk!
{34116}{34186}That's right and let the whole|damn city hear it!
{34181}{34223}That man was right born for this.
{34202}{34276}He's killed 44 men and laid low a|couple of hundred more.
{34242}{34271}Is that right?
{34256}{34266}Right.
{34265}{34298}I should have run him for mayor!
{34314}{34339}Alright, line 'm up.
{34333}{34367}It's election day!
{34473}{34506}Come on, you bastard. We need|your vote.
{34494}{34540}Bastard? I fought for you|nigger...
{34521}{34549}...I lost an arm for you!
{34535}{34577}Well, that's a start. Come on.
{34556}{34601}Rise and shine, rise and shine.
{34585}{34661}This great country of ours, even|hop fiends get their vote.
{34638}{34684}Less heart and more haste,|darling.
{34661}{34685}Where are you going ?
{34673}{34707}I already voted today.
{34694}{34747}Cast for Monk and Tammany, by god!
{34724}{34739}Twice.
{34731}{34747}Twice?
{34743}{34790}Only twice? You call that doing|your civic duty?
{34769}{34787}Come with me.
{34782}{34836}Oh no, you don't. Get back and|sit down.
{34813}{34845}Here's another one!
{34831}{34848}Clean him up good.
{34839}{34909}Shave the beards off boys and send|them back to vote again.
{34874}{34918}Okay boys, vote Tammany.
{34899}{34927}Tammany!
{34913}{34988}What our great city needs is a new|court house.
{34950}{35018}Now I propose it should be a|modest, economical structure.
{34984}{35010}Excuse me one moment.
{34997}{35007}What is it?
{35009}{35101}Monk's already won by 3,000 more|votes, then there are voters.
{35055}{35093}Only 3? Make it 20, 30.
{35074}{35124}We don't need a victory, we need a|Roman triumph.
{35099}{35146}We don't have anymore ballots.
{35129}{35174}Remember the first rule of|politics...
{35151}{35187}...ballots don't make the results...
{35169}{35240}..the counters do. Keep counting.
{35591}{35615}It's from Bill.
{35655}{35667}Monk?
{35910}{35958}Citizens of the Five Points!
{35952}{36011}Mr. Cutting is attempting to|draw me...
{35982}{36009}...into an argument...
{36001}{36040}...that would no doubt end in|bloodshed...
{36021}{36070}...and the compromising of my|office.
{36064}{36090}What do you think?
{36098}{36179}Shall I engage in silence, this|relic of the ancient law...
{36144}{36219}...or, shall I be your chosen|voice...
{36182}{36256}...in a new testament, in a new|world?
{36293}{36316}There you are, Bill.
{36334}{36363}The people have spoken.
{36377}{36447}The very notion of violent|reprisal benumbs them.
{36452}{36465}Come on up.
{36479}{36501}Let's see if we can resolve our...
{36490}{36523}...grievances the democratic way.
{36799}{36888}That my friends, is the minority|vote.
{36868}{36933}Now you tasted my mutton, how do|you like it?
{36920}{36987}Look, I want you to see this.
{37002}{37045}This is you, right here!
{37029}{37115}Notch 45, you Irish bug bastard.
{37212}{37238}Why don't you burn him?
{37225}{37269}See if his ashes turn green.
{37319}{37366}Fortune favours them all!
{37501}{37538}You killed an elected official?
{37533}{37560}Who elected him?
{37547}{37587}You don't know what you've done|to yourself.
{37652}{37683}I know your works.
{37689}{37731}You're neither cold nor hot.
{37717}{37765}So because you are luke warm...
{37741}{37791}...I will spew you out of my|mouth.
{37789}{37851}You can build your filthy world|without me.
{37820}{37884}I took the father, now I'll take|the son.
{37852}{37914}You tell young Vallon, I'm going|to paint...
{37883}{37927}...Paradise square with his blood.
{37911}{37943}Two coats!
{37941}{37999}I'll festoon my sleeping|chamber with his guts.
{37970}{38028}As for you Mr. Tammany|fucking hall...
{37999}{38058}...you come down to the Points|once more...
{38028}{38098}...and you'll be dispatched by my|own hand!
{38095}{38124}Now get back to your|celebration...
{38109}{38148}...and let me eat in peace.
{38129}{38156}I paid you fair.
{38446}{38458}Down!
{38476}{38486}Raise!
{39011}{39035}You son of a bitch!
{39084}{39098}Challenge.
{39124}{39149}Challenge accepted.
{39772}{39800}And then it came...
{39798}{39837}...the first day of the draft.
{39817}{39835}Thomas O'neill.
{39841}{39861}Andrew Lewis.
{39869}{39894}Joseph Flynn.
{39881}{39962}They read out the draftees names|as if they were dead already.
{39946}{39978}J.B. Gleeson.
{39979}{39997}The O'Conell Guard.
{40000}{40017}The Plug Uglies.
{40013}{40021}As for us.
{40017}{40037}The Forty Thieves.
{40029}{40053}The tribes were gathered.
{40054}{40074}The Chichesters.
{40064}{40096}The drums were beating.
{40087}{40105}The Dead Rabbits.
{40105}{40128}The American guard.
{40126}{40150}The Atlantic Guard.
{40142}{40168}The Slaughterhouses.
{40155}{40186}The Bowery Boys.
{40176}{40219}Confederation of American Natives.
{40222}{40244}James Mooney.
{40238}{40268}But all we could see...
{40263}{40300}...was the hand in front of us.
{40281}{40302}Shaun O'Connell.
{40313}{40351}C.W. Morris.
{40361}{40374}When?
{40373}{40401}Whenever you like.
{40392}{40416}Daybreak tomorrow.
{40410}{40421}Ground?
{40427}{40442}Paradise square.
{40451}{40464}Weapons?
{40472}{40503}That I leave up to you.
{40496}{40541}Bricks, bats, axes, knives.
{40539}{40558}Pistols?
{40577}{40601}No pistols.
{40604}{40629}Good boy.
{40661}{40687}Terms are resolved.
{40674}{40700}Counsel is concluded.
{40773}{40807}To hell with your damned draft.
{40794}{40822}Get 'm boys.
{40808}{40834}Rip 'm apart.
{40915}{40950}Kill the rich bastards.
{41020}{41042}Hotel!
{41058}{41101}They're not getting my son!
{41147}{41193}Uptown town at the draft office...
{41178}{41227}...the cops broke a few skulls.
{41210}{41247}And everybody ran away.
{41251}{41290}But the word was spreading...
{41283}{41315}...in the dark.
{41319}{41400}Up on fifth avenue, the Schermerhorns|and their mob...
{41360}{41403}...breathed a little easy.
{41381}{41456}Just a brief blist of anger, over|Mr. Lincoln's draft.
{41419}{41463}Entirely justifiable in my view.
{41447}{41482}There are two sides to that|question.
{41464}{41526}Ther are several sides to that|question, Mr. Schermerhorn.
{41495}{41534}But only one right side.
{41515}{41568}As with any question, it|holds the abuse...
{41541}{41566}...of any executive power.
{41554}{41600}In any case, Mr. Greely...
{41577}{41648}...we can all be thankful, it|wasn't any worse.
{41619}{41659}It may be worse yet, sir.
{41639}{41680}I saw them. I don't know|what to think...
{41659}{41727}What is it you are so fond of|saying, Mr. Tweed?
{41693}{41736}Mr. Greely, you won't like this...
{41715}{41741}...but what is it?
{41728}{41754}I don't remember.
{41741}{41804}You can always hire one half| of the poor...
{41772}{41809}...to kill the other half.
{41924}{41956}I've come to say goodbye.
{41956}{42001}I've booked passage for|California.
{42021}{42072}Jenny, give me one more day and|I'll go with you.
{42056}{42087}You'll be dead by then.
{42091}{42121}What would you have me do?
{42106}{42126}I don't know.
{42164}{42200}This will all be finished|tomorrow.
{42188}{42213}No it won't.
{42254}{42304}This whole place is going to|burn anyway.
{42388}{42469}I've heard of the poor are going|from door to door...
{42429}{42536}...in the Five Points, asking those|supporters for further riots...
{42489}{42541}...to place a candle in the|window.
{42532}{42575}Irish, Poles, Germans.
{42567}{42637}Ah, Mr. Greely, the city is not mad...
{42609}{42666}...I prophesise a dark night.
{42910}{42943}Nobody goes to work today.
{42931}{42976}We're shutting the factories down!
{42953}{42998}When the sun rose next...
{42981}{43026}...the city had split in half.
{43011}{43058}From all over New York|they came...
{43034}{43099}...ironworkers, factory boys,|street cleaners!
{43067}{43112}Irish, Polish, German...
{43089}{43156}...anyone who never cared about|slavery in the Union.
{43129}{43167}Anyone who couldn't buy his way out.
{43161}{43188}Let the sons of the rich...
{43174}{43210}....go and die they cried.
{43198}{43230}Let the sons of the poor...
{43214}{43243}...stay home.
{43248}{43289}The earth was shaking now.
{43281}{43334}But I was about my father's business.
{43488}{43523}Oh, mighty Lord...
{43516}{43568}...you are the dagger in|my hand.
{43555}{43612}Guide my hand on this day of|vengeance.
{43584}{43634}We give thanks to the Lord....
{43614}{43651}...for He is good.
{43639}{43694}With you, the swift cannot flee.
{43667}{43713}Nor the strong escape.
{43690}{43791}Let my sword devour, till its thirst|is quenched with blood....
{43740}{43785}...and my enemy sleeps forever.
{43769}{43824}For you and the God of|retribution.
{43796}{43856}For the Lord crushes the wicked.
{43826}{43870}The Lord is merciful.
{43869}{43944}And his love endures forever.
{43919}{43936}Amen.
{43928}{43945}Amen.
{43936}{43955}Amen.
{44106}{44130}Get the women upstairs!
{44231}{44282}From 18th precinct. The mob is|ransacking houses...
{44257}{44298}....in 27th street and 7th|avenue.
{44277}{44318}We have no force to send.
{44298}{44324}From 15th precinct.
{44311}{44363}All the stores are closing on|8th avenue.
{44337}{44385}From fear of the mob in 17th|street.
{44419}{44431}From 4th.
{44425}{44481}The rioters are attacking|coloured boarding houses...
{44453}{44495}...robbing them and setting them|on fire.
{44474}{44494}From 21st.
{44484}{44531}The mob have just broken open|a gun store...
{44507}{44555}...on 3rd avenue and are arming.
{44627}{44674}Marshall's office on 3rd avenue|is burning down.
{44650}{44683}The police is of no avail.
{44667}{44698}Show yourself, please!
{44682}{44728}Two coloured men brought in|almost dead.
{44705}{44743}There are 50 more outside.
{44724}{44745}They need help.
{44735}{44777}The blacks are being attacked|all over the city.
{44756}{44803}There's the 300 dollar man!
{44782}{44793}Get him!
{44798}{44834}Did your daddy buy you out of|the army!
{44819}{44853}Can he buy me out of the|army too?
{44845}{44892}There is danger of mob|attacking armoury...
{44868}{44918}...corner 21st street, 2nd|avenue.
{44899}{44944}There's about 500 stand of arms|in it.
{45002}{45038}The line is dead. They're trying|to cut all the wires!
{45071}{45083}From 1st.
{45080}{45117}Riot at Pier 4, North River.
{45099}{45132}They have killed negros there.
{45115}{45169}A crowd is here and are going to|destroy the station.
{45189}{45209}Get her bag!
{45204}{45217}Get her bag!
{45238}{45258}From 18th precinct.
{45254}{45283}The mob have attacked the|armoury.
{45268}{45301}...on 2nd avenue an 21st street.
{45285}{45334}There is danger of fire in the|building.
{45313}{45372}All 300 police wounded or|unaccounted for.
{45366}{45376}From 20th.
{45374}{45416}Send 100 men to disperse mob....
{45419}{45460}Building corner 33rd street, 2nd|avenue...
{45444}{45474}...set on fire by the mob.
{45476}{45518}Barnum's American museum on|fire!
{45501}{45524}Animals are escaping.
{45525}{45553}Let go!
{45728}{45820}Gunboat Liberty! An ironclad berth now|lying on the foot of Wall street.
{45774}{45818}They're ready to open fire on|the mob!
{45796}{45836}The mob are now going to 5th|avenue...
{45816}{45852}....to attack the Tribune office.
{45843}{45859}From 16th.
{45851}{45891}The mob is coming down to|station house.
{45871}{45892}We have no men!
{45899}{45941}From 16th. The seventh regiment|has arrived....
{45920}{45950}...on the foot of Canal street.
{45935}{45963}They're on their way to|Bog Wade.
{45968}{46007}The mob is about 4500 strong.
{45993}{46024}They are going to burn down|Harlem Bridge.
{46015}{46047}Harlem Bridge is to be torched!
{46040}{46076}The rats have taken over|the city!
{46115}{46187}From 21st. There's an attack on|the coloured people in 2nd avenue.
{46151}{46201}There's a mob headed for the|coloured orphan's asylum.
{46176}{46212}Send troops to protect the|children.
{46204}{46273}7th Avenue, 28th street. They|have just killed a negro.
{46239}{46255}There's a negro!
{46247}{46267}Get him!
{46257}{46300}Sir, the major general wants to|know what to do....
{46278}{46291}...with the prisoners captured.
{46285}{46307}Prisoners? Don't take any.
{46296}{46332}The mob isn't taking any|prisoners!
{46319}{46342}Put the mob down!
{46331}{46400}Don't take a prisoner till|you've put the mob down!
{46455}{46488}Soldiers now on 38th street.
{46477}{46511}The mob will not disperse!
{46502}{46525}What are your orders?
{46518}{46547}What are your orders?
{46816}{46824}Here the come!
{46855}{46876}Let's stick together!
{46919}{46956}Troop. Halt!
{46951}{46997}Present arms!
{47050}{47084}On your order, Vallon!
{47119}{47178}I order you to disperse.
{47193}{47223}Fire!
{47640}{47675}Fire!
{47847}{47868}Fire!
{48109}{48141}Drive them into the square.
{48163}{48187}Bill!
{48330}{48354}Bill!
{49565}{49586}Bastards!
{49575}{49602}Shang!Hold on!
{49996}{50040}Thank God.
{50032}{50065}I die a true American.
{51532}{51551}Tomorrow morning...
{51541}{51580}...get our people down to|the docks.
{51569}{51622}I want every man and woman|coming off the boats...
{51599}{51637}...given hot soup and bread.
{51680}{51741}We're burying a lot of votes|here tonight.
{51934}{51960}In the end....
{51947}{51992}...they put candles on the|bodies...
{51969}{52037}...so their friends, if they|had any...
{52016}{52054}...could know them in the dark.
{52056}{52115}The city did this free|of charge.
{52111}{52239}Shang, Jimmy Spoils, Hellcat.|McGloin and more.
{52203}{52240}Friend or foe...
{52229}{52272}...it didn't make no difference|now.
{52492}{52531}It was four days and nights...
{52511}{52586}..before the worst of the mob|was finally put down.
{52574}{52633}We never knew how many New|Yorkers died...
{52603}{52670}...that week, before the city|was finally delivered.
{52660}{52754}My father told me we was all|born of blood and tribulation.
{52732}{52818}And so then too, was our|great city.
{52819}{52851}But for those of us who...
{52835}{52896}...lived and died in them|furious days...
{52878}{52922}...it was like everything we|knew...
{52906}{52954}...was mildly swept away.
{52952}{53034}And no matter what they did to|build this city up again...
{53016}{53054}...for the rest of time...
{53062}{53132}...would be like no one ever|knew we were here.
